### ISSUE TITLE
Site is not accesible

### ISSUE THREAD

**Issue by gerroon** [dnomd343/alltube-docker#1]
I cant access the site over the network, I am not running it proxy or reverse proxy.

```
docker run -d --restart always --name alltube -p 24000:80 \
  --env TITLE="Vid" \
  --env CONVERT=ON \
  --env STREAM=ON \
  --env REMUX=ON \
  --env PORT=24000 dnomd343/alltube

```

```
latest: Pulling from dnomd343/alltube
895e193edb51: Pull complete 
9be4925c3b5c: Pull complete 
d794fb2cd40a: Pull complete 
Digest: sha256:64eca9e9aeb0e7dc95637a70465194103766e897cfe60d8686ccbde32a6ecbb8
Status: Downloaded newer image for dnomd343/alltube:latest
4b12749179be502a2e241c822da1d1ec1c9673b9c3461f3b7a18b0968fa39c09
Port: 24000
Remux enabled
Stream enabled
Convert enabled
Title: `Vidy`
yt-dlp version: 2023.03.04
Alltube service is running...
```

**Comment by dnomd343** [comment]
There is a problem with your startup command. It is currently in bridge mode. You can understand it as another independent network. Specifying the environment variable `PORT=24000` will make alltube work on port 24000, but you also specified `-p 24000:80`, which maps port 24000 on the host to port 80 on this network, but it has nothing, so it won't work.

You have two options, the first is to remove `-p 24000:80` and add `--network host`, the second is to remove `--env PORT=24000`, both of them can make alltube work normally, as follows.

```bash
docker run -d --restart always --name alltube --network host \
  --env TITLE="Vid" \
  --env CONVERT=ON \
  --env STREAM=ON \
  --env REMUX=ON \
  --env PORT=24000 dnomd343/alltube
```

```bash
docker run -d --restart always --name alltube -p 24000:80 \
  --env TITLE="Vid" \
  --env CONVERT=ON \
  --env STREAM=ON \
  --env REMUX=ON dnomd343/alltube
```

> PS: the network efficiency of the first scheme is higher.

**Comment by gerroon** [comment]
Hey thanks, that works!.
